(function(){var d,M,A,N,p,O,P,s,t,D,Q,B,R,S,k,E,F,G,H,I,T,u,v,w,q,l,m,n,U,g,J,h,x,r,K,C,y,z,L;g=this;q={};"undefined"!==typeof p?("undefined"!==typeof module&&module.exports&&(p=module.exports=q),p.jshapes=q):g.jshapes=q;h=new dds.Runtime("ws://192.168.0.38:9990");h.ondisconnect=function(a){a=g.document.getElementById("subscribeBtn");console.log("Enabling "+a);a.disabled=!0;g.document.getElementById("publishBtn").disabled=!0;return alert("Connection Failure! Please check your Internet connection")};
h.onconnect=function(){var a;g.document.getElementById("subscribeBtn").disabled=!1;g.document.getElementById("publishBtn").disabled=!1;a=g.document.getElementById("connectBtn");a.innerHTML=" Disconnect";a.onclick=F;return g.document.getElementById("clearTPSBtn").disabled=!1};h.ondisconnect=function(){var a;a=g.document.getElementById("connectBtn");a.innerHTML=" Connect";return a.onclick=E};E=function(){return h.connect(dsconf.dscriptServer)};F=function(){return h.disconnect()};(function(){var a;a=
g.document.getElementById("iShapeCanvas");a.onmousedown=function(a){return console.log("Mouse down event "+a)};a.onmousemove=function(a){return console.log("Mouse move event "+a)};return a.onmouseup=function(a){return console.log("Mouse up event "+a)}})();d={logo:{img:new Image,coord:{x:280,y:300}},bounds:{w:501,h:361},refresh:40,canvas:function(){return g.document.getElementById("iShapeCanvas")},g2d:function(){return g.document.getElementById("iShapeCanvas").getContext("2d")},shapeTopic:function(){return g.document.getElementById("topicSelection").value.toString()},
shapeColor:function(){return g.document.getElementById("colorSelection").value.toString()},shapeSize:function(){return parseInt(g.document.getElementById("topicSize").value.toString(),10)},shapeSpeedX:function(){return parseInt(g.document.getElementById("topicSpeedX").value.toString(),10)},shapeSpeedY:function(){return parseInt(g.document.getElementById("topicSpeedY").value.toString(),10)},shapeHistory:function(){return parseInt(g.document.getElementById("historyDepth").value,10)},shapeHistoryPolicy:function(){return dds.History.KeepLast(parseInt(g.document.getElementById("historyDepth").value,
10))},shapePartitionPolicy:function(){return dds.Partition(g.document.getElementById("partition").value)},shapeReliabilityPolicy:function(){return parseInt(g.document.getElementById("reliability").value.toString(),10)===dds.ReliabilityKind.BestEffort?dds.Reliability.BestEffort:dds.Reliability.Reliable},shapeTimeFilter:function(){var a;a=parseInt(g.document.getElementById("tfilter").value,10);console.log("TimeFilter = "+a);return 0===a?dds.None:new dds.Some(dds.TimeFilter(a))},shapeContentFilter:function(){var a;
a=g.document.getElementById("cfilter").value;console.log("CFilter = "+a);return 0===a.length?dds.None:new dds.Some(dds.ContentFilter(a))},shapeReaderQos:function(){var a,c,b;a=new dds.DataReaderQos(d.shapeReliabilityPolicy(),d.shapePartitionPolicy(),d.shapeHistoryPolicy());c=d.shapeContentFilter();b=d.shapeTimeFilter();a=c!==dds.None?a.add(c.get()):a;return b!==dds.None?a.add(b.get()):a},shapeWriterQos:function(){return new dds.DataWriterQos(d.shapeReliabilityPolicy(),d.shapePartitionPolicy(),d.shapeHistoryPolicy())},
defaultShapeSize:60};d.logo.img.src="./images/logo.png";k={RED:"#cc3333",GREEN:"#99cc66",BLUE:"#336699",ORANGE:"#ff9933",YELLOW:"#ffff66",MAGENTA:"#cc99cc",CYAN:"#99ccff",GRAY:"#666666",WHITE:"#ffffff",BLACK:"#000000"};new dds.DataReaderQos(dds.Reliability.Reliable);new dds.DataWriterQos(dds.Reliability.BestEffort);D=new dds.Topic(0,"Circle","org.omg.dds.demo.ShapeType");K=new dds.Topic(0,"Square","org.omg.dds.demo.ShapeType");L=new dds.Topic(0,"Triangle","org.omg.dds.demo.ShapeType");z=r=t=y=x=s=
null;n=m=l=w=v=u=dds.None;A=dds.bind(function(a){return a.color});M=function(){return function(a,c,b,e,f,d){this.color=a;this.shapesize=c;this.x=b;this.y=e;this.dx=f;this.dy=d}}();U=function(a,c,b,e){var f;f=new M;f.color=a;f.shapesize=c;f.x=Math.floor(Math.random()*d.bounds.w);f.y=Math.floor(Math.random()*d.bounds.h);f.dx=b;f.dy=e;return f};C=function(a){var c;c={};c.color=a.color;c.x=a.x;c.y=a.y;c.shapesize=a.shapesize;return c};G=function(a,c){return function(b){a.fillStyle=k[b.color];a.beginPath();
a.arc(b.x,b.y,b.shapesize/2,0,2*Math.PI,!0);a.fill();a.fillStyle=c;a.beginPath();a.arc(b.x,b.y,b.shapesize/6,0,2*Math.PI,!0);a.closePath();return a.fill()}};H=function(a,c){return function(b){var e;a.fillStyle=k[b.color];a.fillRect(b.x,b.y,b.shapesize,b.shapesize);a.fillStyle=c;e=b.shapesize/3;return a.fillRect(b.x+e,b.y+e,e,e)}};T=function(a,c,b){a.beginPath();a.moveTo(0,0);a.lineTo(c,0);a.lineTo(c-b,-c);return a.closePath()};I=function(a,c){return function(b){var e,f;a.save();e=b.x;f=b.y+b.shapesize;
a.translate(e,f);a.fillStyle=k[b.color];e=b.shapesize;f=b.shapesize/2;T(a,e,f);a.fill();a.restore();a.save();e=b.x+f;f=b.y+1.25*f;a.fillStyle=c;a.beginPath();a.arc(e,f,b.shapesize/6,0,2*Math.PI,!0);a.closePath();a.fill();return a.restore()}};q=function(a){var c;c={};c.x=a.x;c.y=a.y;c.w=c.h=a.shapesize;return c};p=function(a,c){return function(b){var e,f,d;e=a(b);f=b.dx;d=b.dy;e.x+e.w>c.w?(0<f&&(f=-f),0.5<Math.random()&&(d=-d)):e.y+e.h>c.h?(0<d&&(d=-d),0.5<Math.random()&&(f=-f)):0>=e.x?(0>f&&(f=-f),
0.5<Math.random()&&(d=-d)):0>=e.y&&(0>d&&(d=-d),0.5<Math.random()&&(f=-f));b.x+=f;b.y+=d;b.dx=f;b.dy=d;return b}};N=p(function(a){var c,b;b=a.shapesize/2;c={};c.x=a.x-b;c.y=a.y-b;c.w=c.h=a.shapesize;return c},d.bounds);O=p(q,d.bounds);P=p(q,d.bounds);J=function(){return setInterval("animate()",d.refresh)};B=function(a,c,b,d){null!==a&&a.close();null!==b&&b.close();return dds.None};Q=function(){B(s,u,t,l);s=t=null;return u=l=dds.None};R=function(){B(x,v,r,m);x=r=null;return v=m=dds.None};S=function(){B(y,
w,r,n);y=z=null;return w=n=dds.None};this.animate=function(){var a,c,b,e,f,g,h;e=d.g2d();e.fillStyle=k.WHITE;e.fillRect(0,0,d.bounds.w,d.bounds.h);e.drawImage(d.logo.img,d.logo.coord.x,d.logo.coord.y);f=G(e,k.WHITE);a=G(e,k.BLACK);g=H(e,k.WHITE);c=H(e,k.BLACK);h=I(e,k.WHITE);b=I(e,k.BLACK);l.map(function(a){return a.forEach(f)});m.map(function(a){return a.forEach(g)});n.map(function(a){return a.forEach(h)});u.map(function(b){return b.forEach(a)});v.map(function(a){return a.forEach(c)});w.map(function(a){return a.forEach(b)});
l=l.map(function(a){return a.map(N)});m=m.map(function(a){return a.map(O)});n=n.map(function(a){return a.map(P)});l.map(function(a){return a.forEach(function(a){return t.write(C(a))})});m.map(function(a){return a.forEach(function(a){return r.write(C(a))})});return n.map(function(a){return a.forEach(function(a){return z.write(C(a))})})};this.runJShapes=J;this.publishTopic=function(){var a,c,b,e,f,g;g=d.shapeTopic();a=d.shapeColor();f=2*d.shapeSize();c=d.shapeSpeedX();b=d.shapeSpeedY();e=U(a,f,c,b);
c=d.shapeWriterQos();if("Circle"===g)return null===t&&(t=new dds.DataWriter(h,D,c),l=new dds.Some(new dds.DataCache(1))),l.map(function(b){return b.write(a,e)});if("Square"===g)return null===r&&(r=new dds.DataWriter(h,K,c),m=new dds.Some(new dds.DataCache(1))),m.map(function(b){return b.write(a,e)});if("Triangle"===g)return null===z&&(z=new dds.DataWriter(h,L,c),n=new dds.Some(new dds.DataCache(1))),n.map(function(b){return b.write(a,e)})};this.subscribeTopic=function(){var a,c,b;b=d.shapeTopic();
a=d.shapeReaderQos();c=d.shapeHistory();if("Circle"===b&&null===s)return s=new dds.DataReader(h,D,a),u=new dds.Some(new dds.DataCache(c)),u.map(function(a){return A(s,a)});if("Square"===b&&null===x)return x=new dds.DataReader(h,K,a),v=new dds.Some(new dds.DataCache(c)),v.map(function(a){return A(x,a)});if("Triangle"===b&&null===y)return y=new dds.DataReader(h,L,a),w=new dds.Some(new dds.DataCache(c)),w.map(function(a){return A(y,a)})};this.connect=E;this.disconnect=F;this.clearTopicPubSub=function(){switch(d.shapeTopic()){case "Circle":return Q();
case "Square":return R();case "Triangle":return S()}};this.window.onload=function(){return J()}}).call(this);
