// Generated by CoffeeScript 1.6.3
(function() {
  var controllerPath, controllerURL, dsconf, dscriptServer, exports, readerPrefixPath, readerPrefixURL, root, writerPrefixPath, writerPrefixURL;

  root = this;

  dsconf = {};

  if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
      exports = module.exports = dsconf;
    }
    exports.dsconf = dsconf;
  } else {
    root.dsconf = dsconf;
  }

  dscriptServer = 'ws://ec2-54-228-139-59.eu-west-1.compute.amazonaws.com:9990';

  controllerPath = '/dscript/controller';

  controllerURL = dscriptServer + controllerPath;

  readerPrefixPath = '/dscript/reader';

  readerPrefixURL = dscriptServer + readerPrefixPath;

  writerPrefixPath = '/dscript/writer';

  writerPrefixURL = dscriptServer + writerPrefixPath;

  root.dsconf.dscriptServer = dscriptServer;

  root.dsconf.controllerPath = controllerPath;

  root.dsconf.controllerURL = controllerURL;

  root.dsconf.readerPrefixPath = readerPrefixPath;

  root.dsconf.readerPrefixURL = readerPrefixURL;

  root.dsconf.writerPrefixPath = writerPrefixPath;

  root.dsconf.writerPrefixURL = writerPrefixURL;

}).call(this);
