(function(){var m,n,g,h,p,s,t,q,x,u,v,y,z,f,r=function(a,b){return function(){return a.apply(b,arguments)}},w=[].slice;f={};"undefined"!==typeof g?("undefined"!==typeof module&&module.exports&&(g=module.exports=f),g.dds=f):this.dds=f;f.VERSION="0.1.0";q={map:function(a){return q},flatMap:function(a){return q},get:function(){},getOrElse:function(a){return a()},orElse:function(a){return a()},isEmpty:function(){return!0}};v=function(){function a(b){this.value=b}a.prototype.map=function(b){return new a(b(this.value))};
a.prototype.flatMap=function(b){return b(this.value)};a.prototype.get=function(){return this.value};a.prototype.getOrElse=function(b){return this.value};a.prototype.orElse=function(b){return this};a.prototype.isEmpty=function(){return!1};return a}();s=function(){return function(a,b,c){this.did=a;this.tname=b;this.ttype=c}}();h=function(){function a(b,c){this.topic=b;this.qos=c;this.socketDataHandler=r(this.socketDataHandler,this);this.handlers=[];f.ddscriptRuntime.openDataReaderConnection(b,c,this)}
a.prototype.addListener=function(b){var c;c=this.handlers.length;this.handlers=this.handlers.concat(b);return c};a.prototype.removeListener=function(b){var c;c=this.handlers;return this.handlers=c.slice(0,b).concat(c.slice(b+1,c.length))};a.prototype.onDataAvailable=function(b){var c;c=JSON.parse(b.data);return this.handlers.forEach(function(b){return b(c)})};return a}();p=function(){function a(b,c){this.topic=b;this.qos=c;this.socket=f.None;f.ddscriptRuntime.openDataWriterConnection(b,c,this)}
a.prototype.write=function(){var b;b=1<=arguments.length?w.call(arguments,0):[];return this.socket.map(function(c){return b.forEach(function(b){b="string"===typeof b?b:JSON.stringify(b);try{return c.send(b)}catch(a){return console.log(a)}})})};return a}();g=function(){function a(b,c){this.depth=b;this.cache=c;this.fold=r(this.fold,this);!1===(null!=this.cache)&&(this.cache={})}a.prototype.write=function(b,c){var a;a=this.cache[b];a=!1===(null!=a)?[c]:a.length<this.depth?a.concat(c):a.slice(1,a.lenght).concat(c);
return this.cache[b]=a};a.prototype.forEach=function(b){var c,a,e,k;e=this.cache;k=[];for(c in e)a=e[c],k.push(a.forEach(b));return k};a.prototype.map=function(b){var c,d,e,k;d={};k=this.cache;for(c in k)e=k[c],d[c]=e.map(b);return new a(this.depth,d)};a.prototype.filter=function(b){var c,a,e,k,g,l,f,h;e={};h=this.cache;for(a in h){g=h[a];l=0;for(f=g.length;l<f;l++)c=g[l],b(g)&&(k=c);0!==k.length&&(e[a]=k)}return e};a.prototype.filterNot=function(b){return filter(function(c){return!b(c)})};a.prototype.read=
function(){var b,c,a,e;c=[];e=this.cache;for(b in e)a=e[b],c=c.concat(a);return c};a.prototype.take=function(){var b,a,d,e;d=this.cache;this.cache=[];a=[];for(b in d)e=d[b],a=a.concat(e);return a};a.prototype.take=function(b){var a,d,e,k,g,l,f,h,m;e=[];m=this.cache;for(d in m){l=m[d];f=0;for(h=l.length;f<h;f++)a=l[f],b(l)&&(g=a);f=0;for(h=l.length;f<h;f++)a=l[f],b(l)||(k=a);e=e.concat(g);this.cache[d]=k}return e};a.prototype.get=function(b){b=this.cache[b];if(!(void 0===b)(q))return new v(b)};
a.prototype.getOrElse=function(b,a){var d;d=this.cache[b];if(!(void 0===d)(a()))return new v(d)};a.prototype.fold=function(b){var a=this;return function(d){var e,f,g,h;f=b;h=a.cache;for(e in h)g=h[e],f+=g.reduceRight(d);return f}};return a}();this.dds.bind=function(a){return function(b,c){return b.addListener(function(b){return c.write(a(b),b)})}};this.dds.bindWithFun=function(a){return function(b){return function(c,d){return c.addListener(function(c){b(d);return d.write(a(c),c)})}}};this.dds.Topic=
s;this.dds.DataReader=h;this.dds.DataWriter=p;this.dds.DataCache=g;this.dds.None=q;this.dds.Some=v;n={Topic:0,DataReader:1,DataWriter:2};m={OK:0,Error:1,Create:2,Delegate:3,Unregister:4};y=function(a,b,c){return{cid:a,ek:b,sn:c}};z=function(a,b,c){return{did:a,tn:b.tname,tt:b.ttype,qos:c.policies}};g=function(a,b){return function(c,d,e){c=y(a,b,c);d=z(d.did,d,e);return{h:c,b:d}}};this.dds.DSEntityKind=n;this.dds.DSCommandId=m;this.dds.createDataReaderCommand=g(m.Create,n.DataReader);this.dds.createDataWriterCommand=
g(m.Create,n.DataWriter);t={KeepAll:0,KeepLast:1};s={KeepAll:{id:0,k:t.KeepAll},KeepLast:function(a){return{id:0,k:t.KeepLast,v:a}}};u={Reliable:0,BestEffort:1};x={BestEffort:{id:1,k:u.BestEffort},Reliable:{id:1,k:u.Reliable}};h={Volatile:0,TransientLocal:1,Transient:2,Persistent:3};g={Volatile:{id:h.Volatile},TransientLocal:{id:h.TransientLocal},Transient:{id:h.Transient},Persistent:{id:h.Persistent}};p=function(){function a(){var b,a;b=arguments[0];a=2<=arguments.length?w.call(arguments,1):[];console.log(b);
console.log(a);this.policies=a.concat(b);console.log(this.policies)}a.prototype.add=function(){var b;b=1<=arguments.length?w.call(arguments,0):[];return new a(this.policies.concat(b))};return a}();this.dds.HistoryKind=t;this.dds.History=s;this.dds.ReliabilityKind=u;this.dds.Reliability=x;this.dds.Partition=function(){var a;a=arguments[0];return{id:2,vs:(2<=arguments.length?w.call(arguments,1):[]).concat(a)}};this.dds.DurabilityKind=h;this.dds.Durability=g;this.dds.TimeFilter=function(a){return{id:4,
v:a}};this.dds.ContentFilter=function(a){return{id:3,v:a}};this.dds.DataReaderQos=p;this.dds.DataWriterQos=p;g=function(){function a(b,a,d){var e=this;this.controllerURL=b;this.readerURLPrefix=a;this.writerURLPrefix=d;this.handleMessage=r(this.handleMessage,this);this.createDataWriterConnection=r(this.createDataWriterConnection,this);this.createDataReaderConnection=r(this.createDataReaderConnection,this);this.sn=0;this.drmap={};this.dwmap={};console.log("Connecting to: "+this.controllerURL);this.ctrlSock=
new WebSocket(this.controllerURL);this.ctrlSock.onmessage=function(b){return e.handleMessage(b)}}a.prototype.openDataReaderConnection=function(b,a,d){b=f.createDataReaderCommand(this.sn,b,a);this.drmap[this.sn]=d;this.sn+=1;d=JSON.stringify(b);return this.ctrlSock.send(d)};a.prototype.openDataWriterConnection=function(b,a,d){b=f.createDataWriterCommand(this.sn,b,a);this.dwmap[this.sn]=d;this.sn+=1;d=JSON.stringify(b);return this.ctrlSock.send(d)};a.prototype.handleMessage=function(b){var a,d;
console.log("received"+b.data);b=JSON.parse(b.data);b.h.cid===m.OK&&(b.h.ek===n.DataReader?(a=b.b.eid,d=this.readerURLPrefix+"/"+a,a=this.drmap[b.h.sn],d=new WebSocket(d),d.onmessage=a.onDataAvailable,delete this.drmap[b.h.sn]):b.h.ek===n.DataWriter&&(a=b.b.eid,d=this.writerURLPrefix+"/"+a,a=this.dwmap[b.h.sn],d=new WebSocket(d),a.socket=new f.Some(d),delete this.dwmap[b.h.sn]));if(b.h.cid===m.Error)throw b.b.msg;};return a}();this.dds.ddscriptRuntime=new g(dsconf.controllerURL,dsconf.readerPrefixURL,
dsconf.writerPrefixURL);this.dds.Runtime=g}).call(this);
