(function(){var d,I,q,J,k,K,L,r,s,B,h,C,D,E,M,t,u,v,l,m,n,p,N,g,F,w,x,G,y,z,A,H;g=this;l={};"undefined"!==typeof k?("undefined"!==typeof module&&module.exports&&(k=module.exports=l),k.jshapes=l):g.jshapes=l;dds.VERSION="0.1.0";d={logo:{img:new Image,coord:{x:280,y:300}},bounds:{w:501,h:361},refresh:40,canvas:function(){return g.document.getElementById("iShapeCanvas")},g2d:function(){return g.document.getElementById("iShapeCanvas").getContext("2d")},shapeTopic:function(){return g.document.getElementById("topicSelection").value.toString()},
shapeColor:function(){return g.document.getElementById("colorSelection").value.toString()},shapeSize:function(){return parseInt(g.document.getElementById("topicSize").value.toString(),10)},shapeSpeedX:function(){return parseInt(g.document.getElementById("topicSpeedX").value.toString(),10)},shapeSpeedY:function(){return parseInt(g.document.getElementById("topicSpeedY").value.toString(),10)},shapeHistory:function(){return parseInt(g.document.getElementById("historyDepth").value,10)},shapeHistoryPolicy:function(){return dds.History.KeepLast(parseInt(g.document.getElementById("historyDepth").value,
10))},shapePartitionPolicy:function(){return dds.Partition(g.document.getElementById("partition").value)},shapeReliabilityPolicy:function(){return parseInt(g.document.getElementById("reliability").value.toString(),10)===dds.ReliabilityKind.BestEffort?dds.Reliability.BestEffort:dds.Reliability.Reliable},shapeTimeFilter:function(){var a;a=parseInt(g.document.getElementById("tfilter").value,10);console.log("TimeFilter = "+a);return 0===a?dds.None:new dds.Some(dds.TimeFilter(a))},shapeContentFilter:function(){var a;
a=g.document.getElementById("cfilter").value;console.log("CFilter = "+a);return 0===a.length?dds.None:new dds.Some(dds.ContentFilter(a))},shapeReaderQos:function(){var a,c,b;a=new dds.DataReaderQos(d.shapeReliabilityPolicy(),d.shapePartitionPolicy(),d.shapeHistoryPolicy());c=d.shapeContentFilter();b=d.shapeTimeFilter();a=c!==dds.None?a.add(c.get()):a;return b!==dds.None?a.add(b.get()):a},shapeWriterQos:function(){return new dds.DataWriterQos(d.shapeReliabilityPolicy(),d.shapePartitionPolicy(),d.shapeHistoryPolicy())},
defaultShapeSize:60};d.logo.img.src="./images/logo.png";h={RED:"#cc3333",GREEN:"#99cc66",BLUE:"#336699",ORANGE:"#ff9933",YELLOW:"#ffff66",MAGENTA:"#cc99cc",CYAN:"#99ccff",GRAY:"#666666",WHITE:"#ffffff",BLACK:"#000000"};new dds.DataReaderQos(dds.Reliability.Reliable);new dds.DataWriterQos(dds.Reliability.BestEffort);B=new dds.Topic(0,"Circle","org.omg.dds.demo.ShapeType");G=new dds.Topic(0,"Square","org.omg.dds.demo.ShapeType");H=new dds.Topic(0,"Triangle","org.omg.dds.demo.ShapeType");A=x=s=z=w=r=
null;p=n=m=v=u=t=dds.None;q=dds.bind(function(a){return a.color});I=function(){return function(a,c,b,e,f,d){this.color=a;this.shapesize=c;this.x=b;this.y=e;this.dx=f;this.dy=d}}();N=function(a,c,b,e){var f;f=new I;f.color=a;f.shapesize=c;f.x=Math.floor(Math.random()*d.bounds.w);f.y=Math.floor(Math.random()*d.bounds.h);f.dx=b;f.dy=e;return f};y=function(a){var c;c={};c.color=a.color;c.x=a.x;c.y=a.y;c.shapesize=a.shapesize;return c};C=function(a,c){return function(b){a.fillStyle=h[b.color];a.beginPath();
a.arc(b.x,b.y,b.shapesize/2,0,2*Math.PI,!0);a.fill();a.fillStyle=c;a.beginPath();a.arc(b.x,b.y,b.shapesize/6,0,2*Math.PI,!0);a.closePath();return a.fill()}};D=function(a,c){return function(b){var e;a.fillStyle=h[b.color];a.fillRect(b.x,b.y,b.shapesize,b.shapesize);a.fillStyle=c;e=b.shapesize/3;return a.fillRect(b.x+e,b.y+e,e,e)}};M=function(a,c,b){a.beginPath();a.moveTo(0,0);a.lineTo(c,0);a.lineTo(c-b,-c);return a.closePath()};E=function(a,c){return function(b){var e,f;a.save();e=b.x;f=b.y+b.shapesize;
a.translate(e,f);a.fillStyle=h[b.color];e=b.shapesize;f=b.shapesize/2;M(a,e,f);a.fill();a.restore();a.save();e=b.x+f;f=b.y+1.25*f;a.fillStyle=c;a.beginPath();a.arc(e,f,b.shapesize/6,0,2*Math.PI,!0);a.closePath();a.fill();return a.restore()}};l=function(a){var c;c={};c.x=a.x;c.y=a.y;c.w=c.h=a.shapesize;return c};k=function(a,c){return function(b){var e,f,d;e=a(b);f=b.dx;d=b.dy;e.x+e.w>c.w?(0<f&&(f=-f),0.5<Math.random()&&(d=-d)):e.y+e.h>c.h?(0<d&&(d=-d),0.5<Math.random()&&(f=-f)):0>=e.x?(0>f&&(f=-f),
0.5<Math.random()&&(d=-d)):0>=e.y&&(0>d&&(d=-d),0.5<Math.random()&&(f=-f));b.x+=f;b.y+=d;b.dx=f;b.dy=d;return b}};J=k(function(a){var c,b;b=a.shapesize/2;c={};c.x=a.x-b;c.y=a.y-b;c.w=c.h=a.shapesize;return c},d.bounds);K=k(l,d.bounds);L=k(l,d.bounds);F=function(){return setInterval("animate()",d.refresh)};this.animate=function(){var a,c,b,e,f,g,O;e=d.g2d();e.fillStyle=h.WHITE;e.fillRect(0,0,d.bounds.w,d.bounds.h);e.drawImage(d.logo.img,d.logo.coord.x,d.logo.coord.y);f=C(e,h.WHITE);a=C(e,h.BLACK);
g=D(e,h.WHITE);c=D(e,h.BLACK);O=E(e,h.WHITE);b=E(e,h.BLACK);m.map(function(a){return a.forEach(f)});n.map(function(a){return a.forEach(g)});p.map(function(a){return a.forEach(O)});t.map(function(b){return b.forEach(a)});u.map(function(a){return a.forEach(c)});v.map(function(a){return a.forEach(b)});m=m.map(function(a){return a.map(J)});n=n.map(function(a){return a.map(K)});p=p.map(function(a){return a.map(L)});m.map(function(a){return a.forEach(function(a){return s.write(y(a))})});n.map(function(a){return a.forEach(function(a){return x.write(y(a))})});
return p.map(function(a){return a.forEach(function(a){return A.write(y(a))})})};this.runJShapes=F;this.publishTopic=function(){var a,c,b,e,f,g;g=d.shapeTopic();a=d.shapeColor();f=2*d.shapeSize();c=d.shapeSpeedX();b=d.shapeSpeedY();e=N(a,f,c,b);c=d.shapeWriterQos();if("Circle"===g)return null===s&&(s=new dds.DataWriter(B,c),m=new dds.Some(new dds.DataCache(1))),m.map(function(b){return b.write(a,e)});if("Square"===g)return null===x&&(x=new dds.DataWriter(G,c),n=new dds.Some(new dds.DataCache(1))),
n.map(function(b){return b.write(a,e)});if("Triangle"===g)return null===A&&(A=new dds.DataWriter(H,c),p=new dds.Some(new dds.DataCache(1))),p.map(function(b){return b.write(a,e)})};this.subscribeTopic=function(){var a,c,b;b=d.shapeTopic();a=d.shapeReaderQos();c=d.shapeHistory();if("Circle"===b&&null===r)return r=new dds.DataReader(B,a),t=new dds.Some(new dds.DataCache(c)),t.map(function(a){return q(r,a)});if("Square"===b&&null===w)return w=new dds.DataReader(G,a),u=new dds.Some(new dds.DataCache(c)),
u.map(function(a){return q(w,a)});if("Triangle"===b&&null===z)return z=new dds.DataReader(H,a),v=new dds.Some(new dds.DataCache(c)),v.map(function(a){return q(z,a)})};this.window.onload=function(){return F()}}).call(this);
