(function(){var n,p,h,m,s,y,t,u,l,v,q,r,z,A,B,f,C,D,g=function(a,c){return function(){return a.apply(c,arguments)}},w=[].slice;f={};"undefined"!==typeof h?("undefined"!==typeof module&&module.exports&&(h=module.exports=f),h.dds=f):this.dds=f;f.VERSION="0.1.0";l={map:function(a){return l},flatMap:function(a){return l},get:function(){},getOrElse:function(a){return a()},orElse:function(a){return a()},isEmpty:function(){return!0}};r=function(){function a(c){this.value=c}a.prototype.map=function(c){return new a(c(this.value))};
a.prototype.flatMap=function(c){return c(this.value)};a.prototype.get=function(){return this.value};a.prototype.getOrElse=function(c){return this.value};a.prototype.orElse=function(c){return this};a.prototype.isEmpty=function(){return!1};return a}();y=function(){function a(c){this.what=c}a.prototype.map=function(c){throw this.what;};a.prototype.flatMap=function(c){throw this.what;};a.prototype.get=function(){throw this.what;};a.prototype.getOrElse=function(c){throw this.what;};a.prototype.orElse=
function(c){throw this.what;};a.prototype.isEmpty=function(){throw this.what;};return a}();v=function(){function a(c){this.value=c}a.prototype.map=function(c){return c(this.value)};a.prototype.get=function(){return this.value};a.prototype.getOrElse=function(c){return this.value};a.prototype.orElse=function(c){return this};a.prototype.isFailure=function(){return!1};a.prototype.isSuccess=function(){return!0};a.prototype.toOption=function(){return new r(this.value)};a.prototype.recover=function(c){return this};
return a}();t=function(){function a(c){this.exception=c}a.prototype.map=function(c){return l};a.prototype.get=function(){return this.exception};a.prototype.getOrElse=function(c){return c()};a.prototype.orElse=function(c){return c()};a.prototype.isFailure=function(){return!0};a.prototype.isSuccess=function(){return!1};a.prototype.toOption=function(){return l};a.prototype.recover=function(c){return c(this.exception)};return a}();q=function(){return function(a,c,b){this.did=a;this.tname=c;this.ttype=
b}}();m=function(){function a(c,b,a){this.runtime=c;this.topic=b;this.qos=a;this.close=g(this.close,this);this.onDataAvailable=g(this.onDataAvailable,this);this.removeListener=g(this.removeListener,this);this.handlers=[];this.runtime.openDataReaderConnection(b,a,this);this.onclose=function(){};this.closed=!1;this.onconnect=function(){};this.ondisconnect=function(){};this.connected=!1;this.eid=this.runtime.generateEntityId()}a.prototype.addListener=function(c){var b;b=this.handlers.length;this.handlers=
this.handlers.concat(c);return b};a.prototype.removeListener=function(c){var b;b=this.handlers;return this.handlers=b.slice(0,c).concat(b.slice(c+1,b.length))};a.prototype.onDataAvailable=function(c){var b;b=JSON.parse(c.data);return this.handlers.forEach(function(c){return c(b)})};a.prototype.close=function(){console.log("Closing DR "+this);this.closed=!0;this.runtime.closeDataReaderConnection(this);return this.onclose()};return a}();s=function(){function a(c,b,a){this.runtime=c;this.topic=b;this.qos=
a;this.socket=f.None;this.runtime.openDataWriterConnection(b,a,this);this.onclose=function(){};this.closed=!1;this.onconnect=function(){};this.ondisconnect=function(){};this.connected=!1;this.eid=this.runtime.generateEntityId()}a.prototype.write=function(){var c;c=1<=arguments.length?w.call(arguments,0):[];return this.socket.map(function(b){return c.forEach(function(c){c="string"===typeof c?c:JSON.stringify(c);try{return b.send(c)}catch(a){return console.log("Exception while sending data "+a)}})})};
a.prototype.close=function(){this.closed=!0;this.socket=new y("Invalid State Exception: Can't write on a closed DataWriter");this.runtime.closeDataWriterConnection(this);return this.onclose()};return a}();h=function(){function a(c,b){this.depth=c;this.cache=b;this.clear=g(this.clear,this);this.fold=g(this.fold,this);!1===(null!=this.cache)&&(this.cache={})}a.prototype.write=function(c,b){var a;a=this.cache[c];a=!1===(null!=a)?[b]:a.length<this.depth?a.concat(b):a.slice(1,a.lenght).concat(b);return this.cache[c]=
a};a.prototype.forEach=function(c){var b,a,e,k;e=this.cache;k=[];for(b in e)a=e[b],k.push(a.forEach(c));return k};a.prototype.map=function(c){var b,d,e,k;d={};k=this.cache;for(b in k)e=k[b],d[b]=e.map(c);return new a(this.depth,d)};a.prototype.filter=function(c){var b,a,e,k,g,x,h,f;e={};f=this.cache;for(a in f){g=f[a];x=0;for(h=g.length;x<h;x++)b=g[x],c(g)&&(k=b);0!==k.length&&(e[a]=k)}return e};a.prototype.filterNot=function(c){return filter(function(a){return!c(a)})};a.prototype.read=function(){var c,
a,d,e;a=[];e=this.cache;for(c in e)d=e[c],a=a.concat(d);return a};a.prototype.take=function(){var c,a,d,e;d=this.cache;this.cache=[];a=[];for(c in d)e=d[c],a=a.concat(e);return a};a.prototype.takeWithFilter=function(c){var a,d,e,k,g,h,f,l,m;e=[];m=this.cache;for(d in m){h=m[d];f=0;for(l=h.length;f<l;f++)a=h[f],c(a)&&(g=a);f=0;for(l=h.length;f<l;f++)a=h[f],c(a)||(k=a);e=e.concat(g);this.cache[d]=k}return e};a.prototype.get=function(c){c=this.cache[c];if(!(void 0===c)(l))return new r(c)};a.prototype.getOrElse=
function(c,a){var d;d=this.cache[c];if(!(void 0===d)(a()))return new r(d)};a.prototype.fold=function(a){var b=this;return function(d){var e,k,g,f;k=a;f=b.cache;for(e in f)g=f[e],k+=g.reduceRight(d);return k}};a.prototype.clear=function(){return this.cache={}};return a}();this.dds.bind=function(a){return function(c,b){return c.addListener(function(c){return b.write(a(c),c)})}};this.dds.Topic=q;this.dds.DataReader=m;this.dds.DataWriter=s;this.dds.DataCache=h;this.dds.None=l;this.dds.Some=r;this.dds.Success=
v;this.dds.Failure=t;p={Topic:0,DataReader:1,DataWriter:2};n={OK:0,Error:1,Create:2,Delegate:3,Unregister:4};A=function(a,c,b){return{cid:a,ek:c,sn:b}};B=function(a,c,b){return{did:a,tn:c.tname,tt:c.ttype,qos:b.policies}};h=function(a,c){return function(b,d,e){b=A(a,c,b);d=B(d.did,d,e);return{h:b,b:d}}};this.dds.DSEntityKind=p;this.dds.DSCommandId=n;this.dds.createDataReaderCommand=h(n.Create,p.DataReader);this.dds.createDataWriterCommand=h(n.Create,p.DataWriter);u={KeepAll:0,KeepLast:1};t={KeepAll:{id:0,
k:u.KeepAll},KeepLast:function(a){return{id:0,k:u.KeepLast,v:a}}};q={Reliable:0,BestEffort:1};v={BestEffort:{id:1,k:q.BestEffort},Reliable:{id:1,k:q.Reliable}};m={Volatile:0,TransientLocal:1,Transient:2,Persistent:3};h={Volatile:{id:m.Volatile},TransientLocal:{id:m.TransientLocal},Transient:{id:m.Transient},Persistent:{id:m.Persistent}};s=function(){function a(){var a;a=arguments[0];this.policies=(2<=arguments.length?w.call(arguments,1):[]).concat(a)}a.prototype.add=function(){var c;c=1<=arguments.length?
w.call(arguments,0):[];return new a(this.policies.concat(c))};return a}();this.dds.HistoryKind=u;this.dds.History=t;this.dds.ReliabilityKind=q;this.dds.Reliability=v;this.dds.Partition=function(){var a;a=arguments[0];return{id:2,vs:(2<=arguments.length?w.call(arguments,1):[]).concat(a)}};this.dds.DurabilityKind=m;this.dds.Durability=h;this.dds.TimeFilter=function(a){return{id:4,v:a}};this.dds.ContentFilter=function(a){return{id:3,v:a}};this.dds.DataReaderQos=s;this.dds.DataWriterQos=s;z=function(a){return a+
"/dscript/controller"};C=function(a){return a+"/dscript/reader"};D=function(a){return a+"/dscript/writer"};h=function(){function a(a){this.server=a;this.handleMessage=g(this.handleMessage,this);this.openDataWriterConnection=g(this.openDataWriterConnection,this);this.closeDataWriterConnection=g(this.closeDataWriterConnection,this);this.closeDataReaderConnection=g(this.closeDataReaderConnection,this);this.openDataReaderConnection=g(this.openDataReaderConnection,this);this.isClosed=g(this.isClosed,this);
this.isConnected=g(this.isConnected,this);this.close=g(this.close,this);this.disconnect=g(this.disconnect,this);this.establishDroppedDataConnections=g(this.establishDroppedDataConnections,this);this.connect=g(this.connect,this);this.sn=0;this.drmap={};this.dwmap={};this.drconnections={};this.dwconnections={};this.onclose=function(a){};this.onconnect=function(){};this.ondisconnect=function(a){};this.connected=!1;this.closed=!0;this.eidCount=0}a.prototype.generateEntityId=function(){var a;a=this.eidCount;
this.eidCount+=1;return a};a.prototype.connect=function(){var a,b=this;return!1===this.connected?(a=z(this.server),console.log("Connecting to: "+a),this.ctrlSock=l,this.webSocket=new WebSocket(a),this.pendingCtrlSock=new r(this.webSocket),this.pendingCtrlSock.map(function(a){return a.onopen=function(){console.log("Connected to: "+b.server);b.ctrlSock=b.pendingCtrlSock;b.connected=!0;console.log("Re-establishing dropped connection -- if needed");b.establishDroppedDataConnections();return b.onconnect()}}),
this.pendingCtrlSock.map(function(a){return a.onclose=function(a){console.log("The  "+b.server+" seems to have dropped the connection.");b.connected=!1;b.closed=!1;b.ctrlSock=l;return b.ondisconnect(a)}}),this.pendingCtrlSock.map(function(a){return a.onmessage=function(a){return b.handleMessage(a)}})):console.log("Warning: Trying to connect an already connected Runtime")};a.prototype.establishDroppedDataConnections=function(){var a,b,d,e;d=this.drconnections;for(a in d)b=d[a],b.sock.readyState===
b.sock.CLOSED&&(console.log("Establishing dropped connection for data-reader"),this.openDataReaderConnection(b.dr.topic,b.dr.qos,b.dr));d=this.dwconnections;e=[];for(a in d)b=d[a],b.sock.readyState===b.sock.CLOSED?(console.log("Establishing dropped connection for data-writer"),e.push(this.openDataWriterConnection(b.dw.topic,b.dw.qos,b.dw))):e.push(void 0);return e};a.prototype.disconnect=function(){var a,b,d;this.connected=!1;this.ctrlSock.map(function(a){return a.close()});d=this.drconnections;for(a in d)b=
d[a],b.sock.close();d=this.dwconnections;for(a in d)b=d[a],b.sock.close();return this.ondisconnect()};a.prototype.close=function(){var a,b,d,e,k=this;this.ctrlSock.map(function(a){a.close();return k.onclose()});d=this.drconnections;for(a in d)b=d[a],b.dr.close();d=this.dwconnections;e=[];for(a in d)b=d[a],e.push(b.dw.close());return e};a.prototype.isConnected=function(){return this.connected};a.prototype.isClosed=function(){return this.closed};a.prototype.openDataReaderConnection=function(a,b,d){var e;
a=f.createDataReaderCommand(this.sn,a,b);this.drmap[this.sn]=d;this.sn+=1;e=JSON.stringify(a);return this.ctrlSock.map(function(a){return a.send(e)})};a.prototype.closeDataReaderConnection=function(a){var b;b=this.drconnections[a.eid];a=b.dr;b=b.sock;if(void 0!==b)return b.close(),delete this.drconnections[a.eid]};a.prototype.closeDataWriterConnection=function(a){var b;b=this.dwconnections[a.eid];a=b.dw;b=b.sock;if(void 0!==b)return b.close(),delete this.dwconnections[a.eid]};a.prototype.openDataWriterConnection=
function(a,b,d){var e;a=f.createDataWriterCommand(this.sn,a,b);this.dwmap[this.sn]=d;this.sn+=1;e=JSON.stringify(a);console.log("Creating Data Writer on "+this.ctrlSock);this.ctrlSock.map(function(a){return a.send(e)});return console.log("Command sent: "+a)};a.prototype.handleMessage=function(a){var b,d,e;console.log("received"+a.data);a=JSON.parse(a.data);a.h.cid===n.OK&&(a.h.ek===p.DataReader?(d=a.b.eid,d=C(this.server)+"/"+d,b=this.drmap[a.h.sn],d=new WebSocket(d),d.onmessage=b.onDataAvailable,
d.onclose=function(a){b.connected=!1;return b.ondisconnect(a)},delete this.drmap[a.h.sn],d={dr:b,sock:d},this.drconnections[b.eid]=d,b.connected=!0,b.onconnect()):a.h.ek===p.DataWriter&&(d=a.b.eid,d=D(this.server)+"/"+d,e=this.dwmap[a.h.sn],d=new WebSocket(d),d.onclose=function(a){e.socket=new f.Failure(a);e.connected=!1;return e.ondisconnect(a)},e.socket=new f.Success(d),delete this.dwmap[a.h.sn],d={dw:e,sock:d},this.dwconnections[e.eid]=d,e.connected=!0,e.onconnect()));if(a.h.cid===n.Error)throw a.b.msg;
};return a}();this.dds.Runtime=h}).call(this);
